### ISSUE TITLE
Formatting & linting errors

### ISSUE THREAD

**Issue by EdwardSimmons** [arkabokshi/toroidal-fluid-itg#6]
Some of the files have a mix of tabs and spaces used for their indentation, and some of the indentation in the python scripts is inconsistent. This causes my IDE to flare up with a bajillion warnings when editing the files, so I'd like to clean them up for my own sanity.

It's an easy fix, and would make me less nervous about incurring "large" changes for relatively small commits in the future. What do you think?

**Comment by arkabokshi** [comment]
I think it's a good idea! Should we update once the current PR is merged?
